# Define la imagen base a utilizar (Node.js 18.16.0 en su versión "alpine"(mas pequenas))
FROM golang:latest

# Crea y establece el directorio de trabajo dentro del contenedor
WORKDIR /go/src/app


# Copia todo el código fuente de la aplicación al directorio de trabajo del contenedor
COPY . .


# Descarga e instala las dependencias
RUN go mod download


# Compila la aplicación
RUN go build -o mi_aplicacion


# Expone el puerto 2024 en el contenedor (asegúrate de que este puerto coincida con el puerto en el que tu aplicación está escuchando)
EXPOSE 3000

# Comando para iniciar la aplicación cuando se ejecute el contenedor
CMD ["./mi_aplicacion"]

# Construye la imagen Docker (asegúrate de ejecutar el comando desde el directorio que contiene el Dockerfile)
# docker build -t [nombre] clase1_alpine1 .

# Ejecuta un contenedor basado en la imagen que acabas de crear
# docker run -p 2024:2024 [nombre]clase1_alpine1