# Utiliza la imagen oficial de Node.js como base
FROM node:18-alpine as Construccion

# Establece el directorio de trabajo en la ubicación de tu código
WORKDIR /app
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia los archivos de tu aplicación al contenedor
COPY . .

# Construye la aplicación
RUN npm run build

FROM nginx:1.15.2-alpine
COPY --from=Construccion  /app/dist /usr/share/nginx/html

# # Exponer el puerto en el que la aplicación se ejecutará
# EXPOSE 5173

# Comando para ejecutar la aplicación cuando el contenedor se inicia
CMD ["nginx", "-g","daemon off;"]
